/**
 * Export the procedural Phobos and Deimos shape models to OBJ for inspection.
 *
 * The app builds these bodies at runtime through `IrregularBodyGeometry` rather than
 * loading a file, so this is not a build step - it exists so the shape can be opened in
 * the mesh viewer (`npm run mesh-viewer`) and judged, and so a change to the crater or
 * roughness parameters can be eyeballed before it ships. Both paths call the same
 * `buildIrregularSurface`, so the file and the rendered body are the same vertices.
 *
 * Also writes an equirectangular height map per moon, which is the practical way to check
 * that a modelled crater lands on the same spot as the crater in the texture: open the map
 * and the texture at the same size and flip between them.
 *
 *   npm run mars-moons:mesh
 */
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { DEIMOS_SHAPE, PHOBOS_SHAPE } from '../../src/engine/rendering/draw-manager/celestial-bodies/mars-moon-shapes';
import { buildIrregularSurface, IrregularBodyShape, shapeRadius } from '../../src/engine/rendering/irregular-body-shape';

const REPO_ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..', '..');
const OUT_DIR = path.join(REPO_ROOT, 'public', 'meshes');
const MAP_DIR = path.join(REPO_ROOT, 'docs-local', 'mars-moons');
const SEGMENTS = 128;

function toObj(name: string, shape: IrregularBodyShape): string {
  const surface = buildIrregularSurface(shape, SEGMENTS, SEGMENTS);
  const stride = 8;
  const vertexCount = surface.combined.length / stride;
  const lines: string[] = [
    `# ${name} - procedural shape model generated by scripts/mars-moons/export-moon-mesh.ts`,
    '# Units: kilometers. +X faces Mars, +Z is the spin axis.',
    `o ${name}`,
  ];

  for (let i = 0; i < vertexCount; i++) {
    const o = i * stride;

    lines.push(`v ${surface.combined[o].toFixed(5)} ${surface.combined[o + 1].toFixed(5)} ${surface.combined[o + 2].toFixed(5)}`);
  }
  for (let i = 0; i < vertexCount; i++) {
    const o = i * stride + 3;

    lines.push(`vn ${surface.combined[o].toFixed(5)} ${surface.combined[o + 1].toFixed(5)} ${surface.combined[o + 2].toFixed(5)}`);
  }
  for (let i = 0; i < vertexCount; i++) {
    const o = i * stride + 6;

    lines.push(`vt ${surface.combined[o].toFixed(5)} ${surface.combined[o + 1].toFixed(5)}`);
  }
  for (let i = 0; i < surface.indices.length; i += 3) {
    // OBJ indices are 1-based and share the v/vt/vn numbering here.
    const a = surface.indices[i] + 1;
    const b = surface.indices[i + 1] + 1;
    const c = surface.indices[i + 2] + 1;

    lines.push(`f ${a}/${a}/${a} ${b}/${b}/${b} ${c}/${c}/${c}`);
  }

  return `${lines.join('\n')}\n`;
}

/** Grayscale PGM of the radius field on the same lat/lon grid as the texture. */
function toHeightMap(shape: IrregularBodyShape, width = 1024, height = 512): Buffer {
  const radii = new Float64Array(width * height);
  let min = Infinity;
  let max = -Infinity;

  for (let y = 0; y < height; y++) {
    // Row 0 is north, matching an equirectangular texture.
    const theta = Math.PI / 2 - (Math.PI * (y + 0.5)) / height;

    for (let x = 0; x < width; x++) {
      // The geometry puts u = 0.5 at longitude 0, so the map is centered the same way.
      const phi = Math.PI * 2 * ((x + 0.5) / width - 0.5);
      const nx = Math.cos(theta) * Math.cos(phi);
      const ny = Math.cos(theta) * Math.sin(phi);
      const nz = Math.sin(theta);
      const radius = shapeRadius(shape, nx, ny, nz);

      radii[y * width + x] = radius;
      min = Math.min(min, radius);
      max = Math.max(max, radius);
    }
  }

  const pixels = Buffer.alloc(width * height);

  for (let i = 0; i < radii.length; i++) {
    pixels[i] = Math.round(((radii[i] - min) / (max - min)) * 255);
  }

  return Buffer.concat([Buffer.from(`P5\n${width} ${height}\n255\n`), pixels]);
}

fs.mkdirSync(OUT_DIR, { recursive: true });
fs.mkdirSync(MAP_DIR, { recursive: true });

for (const [name, shape] of [
  ['phobos', PHOBOS_SHAPE],
  ['deimos', DEIMOS_SHAPE],
] as const) {
  const objPath = path.join(OUT_DIR, `${name}.obj`);
  const mapPath = path.join(MAP_DIR, `${name}-height.pgm`);

  fs.writeFileSync(objPath, toObj(name, shape));
  fs.writeFileSync(mapPath, toHeightMap(shape));
  console.log(`${name}: ${path.relative(REPO_ROOT, objPath)} + ${path.relative(REPO_ROOT, mapPath)}`);
}
