/**
 * Generates the D1 migration that moves the MMT-9 (Mini-MegaTORTORA) satellite
 * photometry catalog out of src/plugins-pro/data/mmt-ru.txt and into the
 * keeptrack D1 database (served by /v4/admin/mmt on serve-keeptrack-api).
 *
 * Source dump: http://mmt.favor2.info/satellites/download (whitespace-delimited,
 * quoted names, one row per satellite). Conversions applied:
 * - 'nan' magnitude/sigma fields become NULL
 * - the trailing MMT-internal "Id" column becomes the primary key `mmt_id`
 *   (unique across the dump; NORAD/McCants ids collide between catalogues)
 * - everything else is parsed to INTEGER/REAL as declared in the schema
 *
 * The file starts with DELETE FROM so re-applying a regenerated snapshot
 * replaces the dataset wholesale.
 *
 * Usage: npx tsx scripts/generate-mmt-migration.ts [outFile]
 * Default outFile: ../workers/serve-keeptrack-api/migrations/0006_create_mmt_photometry.sql
 * Apply with: wrangler d1 execute keeptrack --remote --file=migrations/0006_create_mmt_photometry.sql
 */
import { readFileSync, writeFileSync } from 'node:fs';
import { resolve } from 'node:path';

const LINE_REGEX = /^(\S+) (\d+) "(.*)" (\S+) (\d+) (\S+) (.*)$/u;
const TRAILING_FIELDS = 13;

const num = (raw: string): string => {
  if (raw === 'nan') {
    return 'NULL';
  }
  const parsed = Number(raw);

  if (Number.isNaN(parsed)) {
    throw new TypeError(`Unparseable number: "${raw}"`);
  }

  return String(parsed);
};

const text = (raw: string): string => `'${raw.replaceAll("'", "''")}'`;

const COLUMNS = [
  'mmt_id', 'catalogue', 'catalog_id', 'name', 'country', 'variability', 'period_s',
  'mag_clear', 'mag_clear_sigma', 'mag_b', 'mag_b_sigma', 'mag_v', 'mag_v_sigma',
  'mag_r', 'mag_r_sigma', 'mag_clear_median', 'mag_clear_min', 'mag_clear_max', 'type',
];

const SCHEMA = `-- MMT-9 (Mini-MegaTORTORA) satellite photometry catalog.
-- One row per tracked object with standard magnitudes normalized to 1000 km range.
-- Generated by keeptrack-space/scripts/generate-mmt-migration.ts - do not hand-edit.
CREATE TABLE IF NOT EXISTS mmt_photometry (
  mmt_id INTEGER PRIMARY KEY,   -- MMT internal satellite id (trailing "Id" column; unique per row)
  catalogue TEXT NOT NULL,      -- 'NORAD' | 'McCants' (analyst objects)
  catalog_id INTEGER NOT NULL,  -- NORAD number, or McCants analyst-catalog number
  name TEXT,
  country TEXT,
  variability INTEGER,          -- 0 = not variable, 1 = aperiodic, 2 = periodic
  period_s REAL,                -- rotation period [s] (0 when not periodic)
  mag_clear REAL,               -- standard magnitude, clear filter
  mag_clear_sigma REAL,
  mag_b REAL,                   -- standard magnitude, Johnson B
  mag_b_sigma REAL,
  mag_v REAL,                   -- standard magnitude, Johnson V
  mag_v_sigma REAL,
  mag_r REAL,                   -- standard magnitude, Johnson R
  mag_r_sigma REAL,
  mag_clear_median REAL,
  mag_clear_min REAL,           -- brightest observed standard magnitude
  mag_clear_max REAL,           -- faintest observed standard magnitude
  type INTEGER                  -- MMT object type code (0-7, per source)
);
CREATE UNIQUE INDEX IF NOT EXISTS idx_mmt_photometry_catalogue_id ON mmt_photometry(catalogue, catalog_id);
CREATE INDEX IF NOT EXISTS idx_mmt_photometry_name ON mmt_photometry(name);

DELETE FROM mmt_photometry;
`;

const lines = readFileSync(resolve(import.meta.dirname, '../src/plugins-pro/data/mmt-ru.txt'), 'utf8')
  .split('\n')
  .map((line) => line.trim())
  .filter((line) => line.length > 0 && !line.startsWith('#'));

const rows: string[] = [];

for (const line of lines) {
  const match = LINE_REGEX.exec(line);

  if (!match) {
    throw new Error(`Unparseable line: ${line}`);
  }
  const [, catalogue, catalogId, name, country, variability, period, rest] = match;
  const trailing = rest.trim().split(/\s+/u);

  if (trailing.length !== TRAILING_FIELDS) {
    throw new Error(`Expected ${TRAILING_FIELDS} trailing fields, got ${trailing.length}: ${line}`);
  }
  const [
    magClear, magClearSigma, magB, magBSigma, magV, magVSigma, magR, magRSigma,
    magClearMedian, magClearMin, magClearMax, type, mmtId,
  ] = trailing;

  rows.push(`(${[
    num(mmtId),
    text(catalogue),
    num(catalogId),
    text(name),
    text(country),
    num(variability),
    num(period),
    num(magClear),
    num(magClearSigma),
    num(magB),
    num(magBSigma),
    num(magV),
    num(magVSigma),
    num(magR),
    num(magRSigma),
    num(magClearMedian),
    num(magClearMin),
    num(magClearMax),
    num(type),
  ].join(', ')})`);
}

const BATCH_SIZE = 250;
const inserts: string[] = [];

for (let i = 0; i < rows.length; i += BATCH_SIZE) {
  inserts.push(`INSERT INTO mmt_photometry (${COLUMNS.join(', ')}) VALUES\n${rows.slice(i, i + BATCH_SIZE).join(',\n')};`);
}

const outFile = resolve(
  process.argv[2] ?? resolve(import.meta.dirname, '../../workers/serve-keeptrack-api/migrations/0006_create_mmt_photometry.sql'),
);

writeFileSync(outFile, `${SCHEMA}\n${inserts.join('\n\n')}\n`);
// eslint-disable-next-line no-console
console.log(`Wrote ${rows.length} rows (${inserts.length} INSERT batches) to ${outFile}`);
