/**
 * Generates the D1 migration that moves the SDLCD photometric observation
 * dataset out of src/plugins-pro/data/sdlcd.ts and into the keeptrack D1
 * database (served by /v4/admin/sdlcd on serve-keeptrack-api).
 *
 * Conversions applied (the source stores every value as a raw string):
 * - numeric fields are trimmed and parsed to REAL/INTEGER
 * - `date` ("22-Mar-2019 23:12:02") becomes ISO 8601 UTC
 * - `decayed: false` becomes decay_date NULL; a date string is kept as-is
 * - `period: "9999"` (the source's "no period found" sentinel) becomes NULL
 * - `perigee: "0"` (the source's "unavailable" sentinel) becomes NULL
 * - `display` is dropped (true on every record; pure passthrough flag)
 * - `period-error` is renamed period_search_step_s: it is the period-search
 *   grid step, not a fitted uncertainty (that is `perr`)
 *
 * Usage: npx tsx scripts/generate-sdlcd-migration.ts [outFile]
 * Default outFile: ../workers/serve-keeptrack-api/migrations/0005_create_sdlcd.sql
 */
import { writeFileSync } from 'node:fs';
import { resolve } from 'node:path';
import sdlcd from '../src/plugins-pro/data/sdlcd';

const MONTHS: Record<string, string> = {
  Jan: '01', Feb: '02', Mar: '03', Apr: '04', May: '05', Jun: '06',
  Jul: '07', Aug: '08', Sep: '09', Oct: '10', Nov: '11', Dec: '12',
};

const toIsoDate = (raw: string): string => {
  const match = /^(\d{2})-([A-Za-z]{3})-(\d{4}) (\d{2}:\d{2}:\d{2})$/u.exec(raw.trim());

  if (!match) {
    throw new TypeError(`Unparseable date: "${raw}"`);
  }
  const month = MONTHS[match[2]];

  if (!month) {
    throw new Error(`Unknown month in date: "${raw}"`);
  }

  return `${match[3]}-${month}-${match[1]}T${match[4]}Z`;
};

const num = (raw: string | undefined): string => {
  if (raw === undefined || raw.trim() === '') {
    return 'NULL';
  }
  const parsed = Number.parseFloat(raw.trim());

  if (Number.isNaN(parsed)) {
    throw new TypeError(`Unparseable number: "${raw}"`);
  }

  return String(parsed);
};

const int = (raw: string | undefined): string => {
  if (raw === undefined || raw.trim() === '') {
    return 'NULL';
  }
  const parsed = Number.parseInt(raw.trim(), 10);

  if (Number.isNaN(parsed)) {
    throw new TypeError(`Unparseable integer: "${raw}"`);
  }

  return String(parsed);
};

const text = (raw: string | undefined): string => (raw === undefined || raw.trim() === '' ? 'NULL' : `'${raw.replaceAll("'", "''")}'`);

const COLUMNS = [
  'id', 'norad', 'object_id', 'object_name', 'object_type', 'decay_date',
  'date', 'filter', 'exposure_s', 'points',
  'apd_s', 'medpd_s', 'modepd_s', 'stdpd_s', 'adu_error', 'mag_error',
  'orbital_period_min', 'inclination_deg', 'perigee_km', 'apogee_km',
  'period_s', 'period_search_step_s', 'perr_s', 'ferr_hz',
  'ampdat_mag', 'amperr_mag', 'ampmath_mag', 'amerr_mag', 'pherr',
  'nmax', 'nmin',
  'lc_file', 'phase_file', 'fit_file', 'data_file', 'data_fit_file',
];

const SCHEMA = `-- SDLCD (Slovak Debris Light Curve Database) photometric observations.
-- One row per light-curve observation of a resident space object.
-- Generated by keeptrack-space/scripts/generate-sdlcd-migration.ts - do not hand-edit.
CREATE TABLE IF NOT EXISTS sdlcd (
  id INTEGER PRIMARY KEY,           -- record number in the source release (NOT stable across releases, NOT a NORAD id)
  norad INTEGER,                    -- NORAD catalog number
  object_id TEXT NOT NULL,          -- compact COSPAR designator, e.g. '00029A' (two-digit year as published)
  object_name TEXT,
  object_type TEXT NOT NULL,        -- 'spacecraft' | 'rocket body' | 'debris'
  decay_date TEXT,                  -- YYYY-MM-DD; NULL = on orbit at observation time
  date TEXT NOT NULL,               -- ISO 8601 UTC start of the observation
  filter TEXT,                      -- photometric band: R/C/V/I/B
  exposure_s REAL,                  -- per-frame exposure time [s]
  points INTEGER,                   -- number of photometric measurements
  apd_s REAL,                       -- mean sampling interval [s]
  medpd_s REAL,                     -- median sampling interval [s]
  modepd_s REAL,                    -- modal sampling interval [s]
  stdpd_s REAL,                     -- sampling-interval standard deviation [s]
  adu_error REAL,                   -- mean per-point uncertainty [ADU]
  mag_error REAL,                   -- mean per-point uncertainty [mag]
  orbital_period_min REAL,          -- revolution period at observation time [min]
  inclination_deg REAL,
  perigee_km REAL,                  -- NULL when the source published its '0' = unavailable sentinel
  apogee_km REAL,
  period_s REAL,                    -- fitted rotation period [s]; NULL when no period converged (source sentinel 9999)
  period_search_step_s REAL,        -- period-search grid step [s] (source field 'period-error'; not a fitted uncertainty)
  perr_s REAL,                      -- fitted period uncertainty [s] (= ferr_hz * period_s^2)
  ferr_hz REAL,                     -- fitted rotation-frequency uncertainty [Hz]
  ampdat_mag REAL,                  -- peak-to-peak amplitude from the raw points [mag]
  amperr_mag REAL,                  -- uncertainty of ampdat_mag [mag]
  ampmath_mag REAL,                 -- peak-to-peak amplitude of the fitted model [mag]
  amerr_mag REAL,                   -- uncertainty of ampmath_mag [mag]
  pherr REAL,                       -- fractional amplitude uncertainty (dimensionless)
  nmax INTEGER,                     -- maxima per rotation in the phase-folded curve
  nmin INTEGER,                     -- minima per rotation in the phase-folded curve
  lc_file TEXT,                     -- raw light-curve plot filename on the source archive
  phase_file TEXT,                  -- phase-folded plot filename
  fit_file TEXT,                    -- fit-overlay plot filename
  data_file TEXT,                   -- raw photometry table filename
  data_fit_file TEXT                -- fitted-model samples table filename
);
CREATE INDEX IF NOT EXISTS idx_sdlcd_norad ON sdlcd(norad);
CREATE INDEX IF NOT EXISTS idx_sdlcd_object_id ON sdlcd(object_id);
CREATE INDEX IF NOT EXISTS idx_sdlcd_object_type ON sdlcd(object_type);
`;

const rows: string[] = [];

for (const [key, rec] of Object.entries(sdlcd)) {
  const periodRaw = rec.period.trim();
  const perigeeRaw = rec.perigee?.trim();

  rows.push(`(${[
    key,
    int(rec.norad),
    text(rec['object-id']),
    text(rec['object-name']),
    text(rec['object-type']),
    rec.decayed === false ? 'NULL' : text(String(rec.decayed)),
    text(toIsoDate(rec.date)),
    text(rec.filter),
    num(rec.exposure),
    int(rec.points),
    num(rec.apd),
    num(rec.medpd),
    num(rec.modepd),
    num(rec.stdpd),
    num(rec['adu-error']),
    num(rec['mag-error']),
    num(rec['orbital-period']),
    num(rec.inclination),
    perigeeRaw === '0' ? 'NULL' : num(perigeeRaw),
    num(rec.apogee),
    periodRaw === '9999' ? 'NULL' : num(periodRaw),
    num(rec['period-error']),
    num(rec.perr),
    num(rec.ferr),
    num(rec.ampdat),
    num(rec.amperr),
    num(rec.ampmath),
    num(rec.amerr),
    num(rec.pherr),
    int(rec.nmax),
    int(rec.nmin),
    text(rec['lc-file']),
    text(rec['phase-file']),
    text(rec['fit-file']),
    text(rec['data-file']),
    text(rec['data-fit-file']),
  ].join(', ')})`);
}

const BATCH_SIZE = 40;
const inserts: string[] = [];

for (let i = 0; i < rows.length; i += BATCH_SIZE) {
  inserts.push(`INSERT INTO sdlcd (${COLUMNS.join(', ')}) VALUES\n${rows.slice(i, i + BATCH_SIZE).join(',\n')};`);
}

const outFile = resolve(
  process.argv[2] ?? resolve(import.meta.dirname, '../../workers/serve-keeptrack-api/migrations/0005_create_sdlcd.sql'),
);

writeFileSync(outFile, `${SCHEMA}\n${inserts.join('\n\n')}\n`);
// eslint-disable-next-line no-console
console.log(`Wrote ${rows.length} rows (${inserts.length} INSERT batches) to ${outFile}`);
